Version 0.2-1

diff --git a/0x0 b/0x0
--- a/0x0
+++ b/0x0
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# 0x0 version 0.1-4
+# 0x0 version 0.2-1
 # Copyright (C) 2020 Pontus Falk
 
 # MIT License
@@ -23,28 +23,84 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-echo "0x0 version 0.1-4. Copyright (C) 2020 by Pontus Falk"
+echo "0x0 version 0.2-1. Copyright (C) 2020 by Pontus Falk"
 echo "License: MIT license"
 echo
 
-if [ "$1" ]; then
-	if [ -f "$1" ]; then
-		echo "Uploading '$1'!"
-        echo
-
-	# Uncomment only one of the following four lines
-	#URL=$(curl -F file=@"$1" -- https://0x0.st)
-	URL=$(curl -# -F file=@"$1" -- https://0x0.st)
-	#URL=$(curl -s -F file=@"$1" -- https://0x0.st)
-	#URL=$(curl -s -S -F file=@"$1" -- https://0x0.st)
-
-	#URL=$(echo foo)
-        echo -n $URL | xclip -i -sel clipboard
-        echo
-        echo "Tjoho, upploading of '$1' is done! The URL is '$URL'!"
-    else
-        echo "Didn't find the file '$1' :("
-    fi
-else
-    echo "Ehh... you have to give a file name! Correct format is '$0 [directory/]filenamn.ext'."
-fi
+case $1 in
+	"--help"|"-h"|"-?")
+		echo "Format: '$0 [command] [directory/]filenamn.ext'."
+		echo
+		echo "Command -#: show progress-bar"
+		echo "        -s: silent mode (supress errors)"
+		echo "        -S: silten mode (show errors)"
+		exit 1
+		;;
+	"-#")
+		if [ "$2" ]; then
+			if [ -f "$2" ]; then
+				echo "Uploading '$2'!"
+				URL=$(curl -# -F file=@"$2" -- https://0x0.st)
+				echo
+				echo -n $URL | xclip -i -sel clipboard
+				echo "Tjoho, uploading of '$2' is done! The URL is '$URL'!"
+			else
+				echo "Didn't find the file '$2' :("
+			fi
+		else
+			echo "Ehh... you have to give a file name!"
+			echo "Correct format is '$0 [directory/]filenamn.ext'."
+			echo "$0 --help for more info."
+		fi
+		;;
+	"-s")
+		if [ "$2" ]; then
+			if [ -f "$2" ]; then
+				echo "Uploading '$2'!"
+				URL=$(curl -s -F file=@"$2" -- https://0x0.st)
+				echo
+				echo -n $URL | xclip -i -sel clipboard
+				echo "Tjoho, uploading of '$2' is done! The URL is '$URL'!"
+			else
+				echo "Didn't find the file '$2' :("
+			fi
+		else
+			echo "Ehh... you have to give a file name!"
+			echo "Correct format is '$0 [directory/]filenamn.ext'."
+			echo "$0 --help for more info."
+		fi
+		;;
+	"-S")
+		if [ "$2" ]; then
+			if [ -f "$2" ]; then
+				echo "Uploading '$2'!"
+				URL=$(curl -s -S -F file=@"$2" -- https://0x0.st)
+				echo
+				echo -n $URL | xclip -i -sel clipboard
+				echo "Tjoho, uploading of '$2' is done! The URL is '$URL'!"
+			else
+				echo "Didn't find the file '$2' :("
+			fi
+		else
+			echo "Ehh... you have to give a file name!"
+			echo "Correct format is '$0 [directory/]filenamn.ext'."
+			echo "$0 --help for more info."
+		fi
+		;;
+	*)
+		if [ "$1" ]; then
+			if [ -f "$1" ]; then
+				echo "Uploading '$1'!"
+				URL=$(curl -F file=@"$2" -- https://0x0.st)
+				echo
+				echo -n $URL | xclip -i -sel clipboard
+				echo "Tjoho, uploading of '$1' is done! The URL is '$URL'!"
+			else
+				echo "Didn't find the file '$1' :("
+			fi
+		else
+			echo "Ehh... you have to give a file name!"
+			echo "Correct format is '$0 [directory/]filenamn.ext'."
+			echo "$0 --help for more info."
+		fi
+esac
